spring:
  datasource:
    username: root
    password: 200204Cwy
    url: jdbc:mysql://localhost:3306/java2final?serverTimezone=UTC&useSSL=false&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9432

